#!/usr/bin/env bash

# Creative Controls
HEPH_MESSENGER_FIRST_LINE="Hello!"

# Application Controls. Best leave alone.
HEPH_GLOBAL_SERVING_HOST=localhost

HEPH_PHASE_0_PROFILE_NOTIFIER_POLLING_INTERVAL=5
HEPH_PHASE_0_PROFILE_NOTIFIER_DESTINATION_PORT=7000

HEPH_PHASE_0_FACE_EXTRACTOR_SERVER_PORT=HEPH_PHASE_0_PROFILE_NOTIFIER_DESTINATION_PORT
HEPH_PHASE_0_FACE_EXTRACTOR_OUTPUT_LOCATION="${PWD}/phase_1_pool"

HEPH_PHASE_1_FACE_SELECTOR_INPUT_LOCATION=HEPH_PHASE_1_FACE_EXTRACTOR_OUTPUT_LOCATION
HEPH_PHASE_1_FACE_SELECTOR_POLLING_INTERVAL=5
HEPH_PHASE_1_FACE_SELECTOR_OUTPUT_LOCATION="${PWD}/phase_2_candidates"

HEPH_PHASE_2_POST_PROCESSOR_INPUT_LOCATION=HEPH_PHASE_1_FACE_SELECTOR_OUTPUT_LOCATION
HEPH_PHASE_2_POST_PROCESSOR_EXECUTION_INTERVAL=5
HEPH_PHASE_2_POST_PROCESSOR_OUTPUT_LOCATION="${PWD}/phase_3_matches"

HEPH_PHASE_3_MESSENGER_INPUT_LOCATION=HEPH_PHASE_2_POST_PROCESSOR_OUTPUT_LOCATION
HEPH_PHASE_3_MESSENGER_EXECUTION_INTERVAL=5

# Enable global absolute-path imports
export PYTHONPATH=$PYTHONPATH:$PWD/heph_modules

# We are starting the applications in a descending order to avoid connection refusal.
python3 heph_modules/face_extractor/face_extractor_server.py ${HEPH_GLOBAL_SERVING_HOST} ${HEPH_PHASE_0_FACE_EXTRACTOR_SERVER_PORT} &
HEPH_PHASE_0_FACE_EXTRACTOR_SERVER_PID=$!

python3 heph_modules/profile_collectors/profile_notifier.py ${HEPH_GLOBAL_SERVING_HOST} ${HEPH_PHASE_0_PROFILE_NOTIFIER_DESTINATION_PORT} ${HEPH_PHASE_0_PROFILE_NOTIFIER_POLLING_INTERVAL} ${PWD} &
HEPH_PHASE_0_PROFILE_NOTIFIER_PID=$!

control_c() {
    echo ""
    echo ""
    echo "Ending program..."

    kill ${HEPH_PHASE_0_FACE_EXTRACTOR_SERVER_PID}
    echo "Terminated Face Extractor Server."

    kill ${HEPH_PHASE_0_PROFILE_NOTIFIER_PID}
    echo "Terminated OKC Profile Collector."

    echo "Program exited."
    exit
}

trap control_c SIGINT

while true ; do
   :
done
